/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Controlador.ControladorPrincipal;
import java.awt.event.ActionListener;

/**
 *
 * @author maria
 */
public class GUIPrincipal extends javax.swing.JFrame {

       /**
        * Creates new form GUIPrincipal
        */
       public GUIPrincipal(ControladorPrincipal controlador) {
              initComponents();
              escuchar(controlador);
              setVisible(true);
       }
       
       public void escuchar(ControladorPrincipal controlador){
              btnInstrucciones.addActionListener(controlador);
              btnJugar.addActionListener( controlador);
              btnSalir.addActionListener( controlador);
       }

       /**
        * This method is called from within the constructor to initialize the
        * form. WARNING: Do NOT modify this code. The content of this method is
        * always regenerated by the Form Editor.
        */
       @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnInstrucciones = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnHistoria = new javax.swing.JButton();
        fondoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BotonInstruccionesS.png"))); // NOI18N
        btnInstrucciones.setText("btnInstrucciones");
        btnInstrucciones.setBorderPainted(false);
        btnInstrucciones.setContentAreaFilled(false);
        jPanel1.add(btnInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 437, 130));

        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BotonJugarS.png"))); // NOI18N
        btnJugar.setText("btnJugar");
        btnJugar.setBorderPainted(false);
        btnJugar.setContentAreaFilled(false);
        jPanel1.add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 432, 160));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BotonSalirS.png"))); // NOI18N
        btnSalir.setText("btnSalir");
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 456, 130));

        btnHistoria.setText("btnHistoria");
        jPanel1.add(btnHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 650, 200, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 760));

        fondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Portada.png"))); // NOI18N
        fondoMenu.setText("jLabel1");
        fondoMenu.setPreferredSize(new java.awt.Dimension(1024, 768));
        getContentPane().add(fondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 410, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

       /**
        * @param args the command line arguments
        */
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistoria;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel fondoMenu;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
